/**
 * Neuroscience Module
 *
 * Cognitive science-inspired memory systems:
 * - Memory States (accessibility model)
 * - Synaptic Tagging & Capture (retroactive importance)
 * - Spreading Activation (associative retrieval)
 * - Importance Signals (multi-factor scoring)
 * - Context Memory (encoding specificity)
 */

// Memory States
export {
  MemoryState,
  TransitionReason,
  STATE_ACCESSIBILITY,
  DEFAULT_ACTIVE_DECAY_HOURS,
  DEFAULT_DORMANT_DECAY_DAYS,
  DEFAULT_SUPPRESSION_HOURS,
  COMPETITION_SIMILARITY_THRESHOLD,
  SUPPRESSION_STRENGTH_FACTOR,
  MAX_STATE_HISTORY_SIZE,
  STRONG_CUE_THRESHOLD,
  type StateTransition,
  type StateTimeAccumulator,
  type MemoryLifecycle,
  type CompetitionResult,
  type MemoryCandidate,
  getAccessibilityMultiplier,
  isRetrievable,
  requiresStrongCue,
  isBlocked,
  createLifecycle,
  recordAccess,
  transitionTo,
  suppressFromCompetition,
  tryReactivateWithCue,
  applyTimeDecay,
  calculateAccessibility,
  batchUpdateLifecycles,
  getStateStats,
  CompetitionManager,
} from './memory-states.js';

// Synaptic Tagging
export {
  DecayFunction,
  ImportanceEventType,
  DEFAULT_BACKWARD_HOURS,
  DEFAULT_FORWARD_HOURS,
  DEFAULT_TAG_LIFETIME_HOURS,
  DEFAULT_PRP_THRESHOLD,
  DEFAULT_MIN_TAG_STRENGTH,
  DEFAULT_MAX_CLUSTER_SIZE,
  IMPORTANCE_BASE_STRENGTHS,
  CAPTURE_RADIUS_MULTIPLIERS,
  type SynapticTag,
  type ImportanceEvent,
  type CaptureWindowConfig,
  type CapturedMemory,
  type ImportanceCluster,
  type TaggingStatistics,
  applyDecay,
  calculateCaptureProbability,
  createTag,
  updateTagStrength,
  isTagActive,
  isTagEligible,
  createImportanceEvent,
  SynapticTaggingSystem,
} from './synaptic-tagging.js';

// Spreading Activation
export {
  LinkType,
  DEFAULT_DECAY_FACTOR,
  DEFAULT_MIN_ACTIVATION,
  DEFAULT_MAX_HOPS,
  MAX_ACTIVATION,
  type AssociationEdge,
  type ActivationNode,
  type ActivatedMemory,
  type ActivationConfig,
  createEdge,
  createNode,
  reinforceEdge,
  decayEdge,
  findShortestPath,
  getStronglyConnected,
  ActivationNetwork,
} from './spreading-activation.js';

// Importance Signals
export {
  DEFAULT_DECAY_RATE,
  MIN_IMPORTANCE,
  MAX_IMPORTANCE,
  HELPFUL_BOOST,
  UNHELPFUL_PENALTY,
  DEFAULT_GRACE_PERIOD_DAYS,
  DEFAULT_RECENCY_HALF_LIFE_DAYS,
  IMPORTANCE_WEIGHTS,
  type UsageEvent,
  type ImportanceScore,
  type ImportanceDecayConfig,
  createImportanceScore,
  calculateFinalScore,
  onRetrieved,
  applyRecencyDecay,
  applyUsageDecay,
  setBaseImportance,
  setConnectionImportance,
  calculateNoveltyScore,
  calculateEmotionalImportance,
  ImportanceTracker,
} from './importance-signals.js';

// Context Memory
export {
  ProjectType,
  Framework,
  type GitContext,
  type FileContext,
  type WorkingContext,
  type ContextSimilarity,
  type EncodingContext,
  detectProjectType,
  getExtensions,
  isTestFile,
  extractModule,
  createFileContext,
  createWorkingContext,
  calculateContextSimilarity,
  boostByContext,
  ContextMemoryStore,
} from './context-memory.js';

// Hippocampal Index
export {
  COMPRESSED_DIMENSION,
  ORIGINAL_DIMENSION,
  SCORE_WEIGHTS,
  TEMPORAL_HALF_LIFE_HOURS,
  FREQUENTLY_ACCESSED_THRESHOLD,
  RECENTLY_CREATED_HOURS,
  HIGH_RETENTION_THRESHOLD,
  DEFAULT_MIN_SIMILARITY,
  type MemoryBarcode,
  type TemporalMarker,
  type ImportanceFlags,
  type ContentPointer,
  type ContentPointerType,
  type IndexLink,
  type IndexLinkType,
  type MemoryIndex,
  type IndexQuery,
  type IndexMatch,
  type FullMemory,
  generateBarcode,
  compressEmbedding,
  expandEmbedding,
  createImportanceFlags,
  calculateImportanceScore,
  calculateTemporalScore,
  indexMemory,
  HippocampalIndexManager,
} from './hippocampal-index.js';

// Predictive Retrieval
export {
  INTEREST_DECAY_ALPHA,
  DAILY_DECAY_FACTOR,
  MAX_QUERY_HISTORY,
  MAX_CO_ACCESS_PER_MEMORY,
  SESSION_TIMEOUT_MS,
  PREDICTION_WEIGHTS,
  MIN_PREDICTION_CONFIDENCE,
  type PredictionReason,
  type PredictedMemory,
  type QueryPattern,
  type TemporalPatterns,
  type ProjectContext,
  type SessionContext,
  type UserModel,
  createTemporalPatterns,
  createSessionContext,
  createUserModel,
  PredictiveRetrievalSystem,
} from './predictive-retrieval.js';

// Prospective Memory
export {
  ESCALATION_THRESHOLD_HOURS,
  DEFAULT_SNOOZE_MINUTES,
  MAX_REMINDERS_BEFORE_ESCALATION,
  NLU_TIME_KEYWORDS,
  NLU_DURATION_KEYWORDS,
  NLU_EVENT_KEYWORDS,
  NLU_PRIORITY_KEYWORDS,
  type Priority,
  type IntentionStatus,
  type TriggerPattern,
  type ContextPattern,
  type RecurrencePattern,
  type IntentionTrigger,
  type Intention,
  type Context,
  createIntention,
  getPriorityValue,
  isOverdue,
  shouldEscalate,
  escalatePriority,
  checkTimeTrigger,
  checkDurationTrigger,
  checkEventTrigger,
  checkContextTrigger,
  checkRecurringTrigger,
  matchesPattern,
  matchesContextPattern,
  createFromText,
  ProspectiveMemoryManager,
} from './prospective-memory.js';
